<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Router</title>
</head>

<body>
    <?= $this->section('content') ?>
    <pre>
        <code>
            <div class="codigo"></div>
        </code>
    </pre>
    <script>
        if (document.querySelector('.home')) {
            fetch('/api/antonio/')
                .then((response) => {
                    if (response.status !== 200) {
                        throw new Error(response.status + ' ' + response.statusText)
                    }
                    return response.json()
                })
                .then((data) => {
                    document.querySelector('.codigo').innerHTML = JSON.stringify(data)
                })
                .catch((e) => {
                    console.error('ERROR: ' + e.message)
                })
        }
    </script>
</body>

</html>